### ISSUE TITLE
swirl stopped working

### ISSUE THREAD

**Issue by mjdata** [swirldev/swirl#384]
swirl stopped working with the following messages:

"warning messages from top-level task callback 'mini'
Warning message:
In readLines(input) :
  incomplete final line found on 'C:/myRlib/swirl/Courses/Statistical_Inference/Probability2/lesson'"

And then after resumed with swirl(), again:

"Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ

| Leaving swirl now. Type swirl() to resume."

**Comment by seankross** [comment]
Thank you for catching this! I believe I just fixed it, but you will need to reinstall the course using: `install_from_swirl("Statistical Inference")`. Please let me know that this works for you.

**Comment by mjdata** [comment]
Hello, Sean Kross,
Thank you very much for fixing the problems  in swirl and for telling me about that.  It works now!  Otherwise I could probably fail to submit before the due time.  Finally I was able to submit swirl assignments and completed them successfully this evening.  Thank you again. 
-- jm
 
Date: Sat, 9 Jan 2016 09:15:33 -0800

**Comment by seankross** [comment]
Good to know! If you have any other questions feel free to get in touch.

**Comment by mjdata** [comment]
Hi, Swirl team,
 
swirl stopped working in Statistical Inference Hypothesis Testing with the following messages:
|Would you like to continue with one of these lessons?
 1: Statistical Inference Hypothesis Testing
 2: No. Let me start something new.
 Selection: 1
 | Attemping to load lesson dependencies...
 | Package gplot2 loaded correctly!
| Here's a plot to show what we mean. The shaded portion
 | represents 5% of the area under the curve and those X values in
 | it are those for which the probability that X>C is 5%.
Error in layer("area", mapping = aes(x = ifelse(x > qnorm(0.95, sd = 2),  : 
  unused argument (geom_params = list(fill = "red", alpha = 0.5))
| Leaving swirl now. Type swirl() to resume.
 
packageVersion("swirl")
[1] ?.2.21? Would you please fix the problem in swirl Statistal Inference Hypothesis Testing?Thanks. -- Jie
 
Date: Sat, 9 Jan 2016 21:02:47 -0800

**Comment by rkarato** [comment]
Hi, I'm getting a similar error in another course. I tried to reinstall the course, but still the same error.

Please see below:


> swirl()

| Welcome to swirl!

| Please sign in. If you've been here before, use the same name as you did then. If you are
| new, call yourself something unique.

What shall I call you? R

| Would you like to continue with one of these lessons?

1: Exploratory Data Analysis GGPlot2 Part1
2: Exploratory Data Analysis K Means Clustering
3: No. Let me start something new.

Selection: 2

| Attemping to load lesson dependencies...

| Package ‘ggplot2’ loaded correctly!

| Package ‘fields’ loaded correctly!

| Package ‘jpeg’ loaded correctly!

| Package ‘datasets’ loaded correctly!

Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ

| Leaving swirl now. Type swirl() to resume.

> install_from_swirl("Exploratory Data Analysis")

| Course installed successfully!

> swirl()

| Welcome to swirl!

| Please sign in. If you've been here before, use the same name as you did then. If you are
| new, call yourself something unique.

What shall I call you? R

| Would you like to continue with one of these lessons?

1: Exploratory Data Analysis GGPlot2 Part1
2: Exploratory Data Analysis K Means Clustering
3: No. Let me start something new.

Selection: 2

| Attemping to load lesson dependencies...

| Package ‘ggplot2’ loaded correctly!

| Package ‘fields’ loaded correctly!

| Package ‘jpeg’ loaded correctly!

| Package ‘datasets’ loaded correctly!

Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
@rkarato does this error occur for you as soon as you begin the lesson?

**Comment by rkarato** [comment]
Yes. I was about to submit the lesson when I got an error related to my proxy password expired. Swirl ended. I fixed my proxy configuration and now immediately when I start the lesson I get the xy.coords message. Tried to debug and what I notice is that x's value is pointing to some file on my file system.

**Comment by rkarato** [comment]
Not sure if helps, but see the value of x while debugging xy.coord
[swirlerror.txt](https://github.com/swirldev/swirl/files/122716/swirlerror.txt)

**Comment by seankross** [comment]
@rkarato 

Can you run the following code line-by-line and let me know if you encounter any errors?

```r
library(fields)
library(swirl)

path_to_course <- file.path(find.package("swirl"),"Courses/Exploratory_Data_Analysis/Hierarchical_Clustering")
try(dev.off(),silent=TRUE)
plot.new()

pathtofile <- function(fileName){
  mypath <- file.path(find.package("swirl"),
                      "Courses/Exploratory_Data_Analysis/Hierarchical_Clustering/",
                      fileName)
}

fxfer <- function(fileName){
  mypath <- pathtofile(fileName)
  file.copy(mypath,fileName)
}

myedit <- function(fname){
  mypath <- pathtofile(fname)
  file.edit(mypath)
}

mdist <- function(x,y,cx,cy){
  distTmp <- matrix(NA,nrow=3,ncol=12)
  distTmp[1,] <- (x-cx[1])^2 + (y-cy[1])^2
  distTmp[2,] <- (x-cx[2])^2 + (y-cy[2])^2
  distTmp[3,] <- (x-cx[3])^2 + (y-cy[3])^2  
  return(distTmp)
}
set.seed(1234);
x <- rnorm(12,mean=rep(1:3,each=4),sd=0.2)
y <- rnorm(12,mean=rep(c(1,2,1),each=4),sd=0.2)
dataFrame <- data.frame(x=x,y=y)
dataMatrix <- as.matrix(dataFrame)
distxy <- dist(dataFrame)
cx <- c(1,1.8,2.5)
cy <- c(2,1,1.5)
cmat <- matrix(c(cx,cy),nrow=2,byrow=TRUE) 

distTmp <- mdist(x,y,cx,cy)
newClust <- apply(distTmp,2,which.min)
cols1 <- c("red","orange","purple")
newCx <- tapply(x,newClust,mean)
newCy <- tapply(y,newClust,mean)
distTmp2 <- mdist(x,y,newCx,newCy)
newClust2 <- apply(distTmp2,2,which.min)
finalCx <- tapply(x,newClust2,mean)
finalCy <- tapply(y,newClust2,mean)
kmObj <- kmeans(dataFrame,3)
```

**Comment by rkarato** [comment]
Sure. No error messages
[swirlerror01.txt](https://github.com/swirldev/swirl/files/124241/swirlerror01.txt)

**Comment by seankross** [comment]
@rkarato I'm still trying to think of what else could be going on here. Have you tried uninstalling swirl (`remove.packages("swirl")`) and then installing the course again?

Sean

**Comment by rkarato** [comment]
Hi Sean, reinstalling swirl seems to have solved the issue. I'll do the exercise again and see if the error returns.
[swirlerror02.txt](https://github.com/swirldev/swirl/files/125258/swirlerror02.txt)

Thanks!

**Comment by seankross** [comment]
No problem!

**Comment by rishiayri** [comment]
Thanks,
I removed and removed and reinstalled the package and it appears to be working at that stage.

Rishi.

**Comment by seankross** [comment]
:+1:

**Comment by mrcouthy** [comment]
Giving a different name when asked for name in What shall I call you?  Solved it for me

**Comment by ilovecee** [comment]
This error occurs when you want to resume the last session for particular courses. Let's say you entered "bye()" in a middle of "Hierarchical Clustering" and exited. Now you reenter Swirl and continue the class and Swirl tries to deliver you to the last checkpoint. This is when the error happens. Hence a new name would help you get out of this loop.

**Comment by clawsar** [comment]
This is crazy.  I continue to have this problem, and it happens for multiple new names.  It seems the token needs to be refreshed immediately before submission to have any hope of success, and even then I've had this happen.  I have taken the same k Means lesson in Swirl 5 times and have yet to get it to go through.  Either a failed to receive handshake error stops the initial submission, then the xy.coords length differ error stops resubmission.

**Comment by MonicaCabreraP** [comment]
> (`remove.packages("swirl")`)

That worked for me- thanks
